// H5 web app
var h5 = new H5();
h5.whenAddPage = function(){
	this.addComponent('slide_up',{
		bg:"footer.png",
		css:{
			opacity:0,
			left:0,
			bottom:0,
			zIndex:'999',
			width:'100%',
			height:'20px'
		},
		animateIn:{
			opacity:1
		},
		animateOut:{
			opacity:0	
		}
		
	});
};

h5
.addPage('face')
	.addComponent('topic',{
		width:395,
		height:130,
		center:true,
		bg:'face_logo.png',
		css:{
			opacity:0
		},
		animateIn:{
			opacity:1,
			top:'10%'
		},
		animateOut:{
			opacity:0,
			top:0
		}
	})
	.addComponent('slogo',{
		width:365,
		height:99,
		center:true,
		bg:'face_slogan.png',
		css:{
			opacity:0
		},
		animateIn:{
			opacity:1,
			top:'28%'
		},
		animateOut:{
			opacity:0,
			top:0
		},
		delay:500
	})
	.addComponent('face_img_left',{
		width:370,
		height:493,
		bg:'face_img_left.png',
		css:{
			opacity:0,
			bottom:'-38%',
			left:'-10%'
		},
		animateIn:{
			opacity:1,
			bottom:0,
			left:0
		},
		animateOut:{
			opacity:0,
			bottom:'-38%',
			left:'-10%'
		},
		delay:1000	
	})
	.addComponent('face_img_right',{
		width:276,
		height:449,
		bg:'face_img_right.png',
		css:{
			opacity:0,
			bottom:'-38%',
			right:'-10%'
		},
		animateIn:{
			opacity:1,
			bottom:0,
			right:0
		},
		animateOut:{
			opacity:0,
			bottom:'-38%',
			right:'-10%'
		},
		delay:1500	
	})
.addPage()
	.addComponent('caption',{text:'核心理念'})
	.addComponent('theme',{
		text:'IT教育网 = 只学有用的',
		width:400,
		height:50,
		center:true,
		css:{
			top:'20%',
			fontSize:'16px',
			color:'#ff4343',
			textAlign:'center',
			opacity:0,
		},
		animateIn:{
			opacity:1,
			top:'30%'
		},
		animateOut:{
			opacity:0,
			top:'20%'
		}
		
	})
	.addComponent('description',{
		text:'2013年，IT教育网的诞生引领中国IT职业从教育进入新时代。',
		width:521,
		height:335,
		bg:'description_bg.gif',
		center:true,
		css:{
			top:'60%',
			fontSize:'16px',
			color:'#ff4343',
			padding:'15px 10px',
			color:'#fff',
			opacity:0,
		},
		animateIn:{
			opacity:1,
			top:'37%'
		},
		animateOut:{
			opacity:0,
			top:'60%'
		},
		delay:500
		
	})
	.addComponent('people',{
		width:515,
		height:305,
		center:true,
		bg:'p1_people.png',
		css:{
			opacity:0,
			bottom:0
		},
		animateIn:{
			opacity:1,
			bottom:'7%'
		},
		animateOut:{
			opacity:0,
			bottom:0
		},
		delay:1000
	})
.addPage()
	.addComponent('caption',{text:'课程方向分布'})
	.addComponent('theme',{
		text:'课程分布前端开发占到40%',
		width:400,
		height:50,
		center:true,
		css:{
			top:'25%',
			fontSize:'16px',
			color:'#000',
			textAlign:'center',
			opacity:0,
		},
		animateIn:{
			opacity:1,
			top:'35%'
		},
		animateOut:{
			opacity:0,
			top:'25%'
		},
		delay:2600
	})
	.addComponent('polyline',{
		type:'polyline',
		width:566,
		height:366,
		step:10,
		data:[
			['javascript',0.4,'#ff2277'],
			['html5',0.2],
			['css3',0.5],
			['jquery',0.3],
			['nodejs',0.2]
		],
		css:{
			top:'30%',
			left:50,
			opacity:0
		},
		animateIn:{top:'50%',opacity:1},
		animateOut:{top:'30%',opacity:0},
		center:true
	})
.addPage()
	.addComponent('caption',{text:'移动开发'})
	.addComponent('theme',{
		text:'移动开发课程中Android比例最大',
		width:500,
		height:50,
		center:true,
		css:{
			bottom:'15%',
			fontSize:'16px',
			color:'#000',
			textAlign:'center',
			opacity:0,
		},
		animateIn:{
			opacity:1,
			bottom:'25%'
		},
		animateOut:{
			opacity:0,
			bottom:'15%'
		},
		delay:2000
	})
	.addComponent('pie',{
		type:'pie',
		width:566,
		height:366,
		step:10,
		data:[
			['Android',0.71,'#ff7676'],
			['Unity',0.02,'#ffad69'],
			['Cocos2d ',0.02,'#99c0ff'],
			['IOS',0.25,'#5ddbd8']
		],
		css:{
			top:'20%',
			left:50,
			opacity:0
		},
		animateIn:{top:'35%',opacity:1},
		animateOut:{top:'20%',opacity:0},
		center:true
	})
.addPage()
	.addComponent('caption',{text:'前端开发'})
	.addComponent('bar',{
		type:'bar',
		width:400,
		height:400,
		data:[
			['javascript',0.4,'#ff7676'],
			['html5',0.1],
			['css3',0.1],
			['jquery',0.4],
			['Node.js',0.3],
			['Bootstrap',0.02],
			['AngularJS',0.2],
			['Webapp',0.04]
		],
		css:{
			top:'20%',
			left:'25%',
			opacity:0
		},
		animateIn:{top:'35%',opacity:1},
		animateOut:{top:'20%',opacity:0}
	})
.addPage()
	.addComponent('caption',{text:'后端处理'})
	.addComponent('radar',{
		type:'radar',
		width:466,
		height:466,
		data:[
			['PHP',0.3,'#ff2277'],
			['GO',0.15],
			['C++',0.46],
			['C',0.3],
			['Python',0.38],
			['JAVA',0.46],
			['Linux',0.1]
		],
		css:{
			top:'20%',
			opacity:0
		},
		animateIn:{top:'45%',opacity:1},
		animateOut:{top:'20%',opacity:0},
		center:true
	})
.addPage('tail')
	.addComponent('tail_logo',{
		width:395,
		height:129,
		center:true,
		bg:'tail_logo.png',
		css:{
			opacity:0,
			top:0
		},
		animateIn:{
			opacity:1,
			top:'30%'
		},
		animateOut:{
			opacity:0,
			top:0
		}
	})
	.addComponent('tail_slogan',{
		width:314,
		height:46,
		center:true,
		bg:'tail_slogan.png',
		css:{
			opacity:0,
			top:'40%'
		},
		animateIn:{
			opacity:1,
			top:'50%'
		},
		animateOut:{
			opacity:0,
			top:'40%'
		},
		delay:500
	})
	.addComponent('tail_share',{
		width:128,
		height:120,
		bg:'tail_share.png',
		css:{
			top:'5%',
			right:'10%',
			opacity:0,
		},
		animateIn:{
			opacity:1,
			right:'10%'
		},
		animateOut:{
			opacity:0,
			right:'0'
		},
		delay:1000
	})
	.addComponent('back',{
		width:128,
		height:120,
		bg:'tail_back.png',
		center:true,
		onclick:function(){
			$.fn.fullpage.moveTo(1);
		}
	})
.loader(["imgs/face_bg.png","imgs/description_bg.gif","imgs/face_img_left.png",
		 "imgs/face_img_right.png","imgs/face_logo.png","imgs/face_slogan.png",
		 "imgs/footer.png","imgs/p1_people.png","imgs/footer.png","imgs/footer.png",
		 "imgs/footer.png","imgs/footer.png","imgs/page_bg.png","imgs/page_caption_bg.png",
		 "imgs/tail_back.png","imgs/tail_logo.png","imgs/tail_share.png","imgs/tail_slogan.png"]);
